### PR TITLE
Handling tables.exceptions.HDF5ExtError

### PR DESCRIPTION
**Pull request by Elisa-Visentin**
I'm testing it on MCs and it seems to be working, but check it before merging, please (exception handling isn't my thing, but I need it to finish my analysis)

### CODE REVIEW

**Comment by aleberti** [comment]
Can you attach (or post somewhere) one MC file causing the problem?

**Comment by YoshikiOhtani** [comment]
Hi, could you please tell me which files show `HDF5ExtError`? I would like to know what causes this error and fix it, rather than skipping the files with this solution (sorry if you already reported in the meetings and if I just missed it...).

**Comment by Elisa-Visentin** [comment]
Hi, 
thanks, this is one of the files:

/fefs/aswg/workspace/elisa.visentin/MAGIC_LST_analysis/Crab_test_mcp/DL1_stereo/MC/gamma_test/theta_60.528_az_251.19/dl1_stereo_gamma_zd_60.528deg_az_251.19deg_LST1_MAGIC1_MAGIC2_run1601.h5

```
Traceback (most recent call last):
  File "merge_hdf_files.py", line 294, in <module>
    main()
  File "merge_hdf_files.py", line 285, in main
    merge_hdf_files(args.input_dir, args.output_dir, args.run_wise, args.subrun_wise)
  File "merge_hdf_files.py", line 243, in merge_hdf_files
    write_data_to_table(file_mask, output_file)
  File "merge_hdf_files.py", line 91, in write_data_to_table
    with tables.open_file(input_file) as f_input:
  File "/home/elisa.visentin/mambaforge-pypy3/envs/magic-lst1/lib/python3.8/site-packages/tables/file.py", line 300, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/home/elisa.visentin/mambaforge-pypy3/envs/magic-lst1/lib/python3.8/site-packages/tables/file.py", line 750, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 486, in tables.hdf5extension.File._g_new
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 620, in H5Fopen
    unable to open file
  File "H5VLcallback.c", line 3501, in H5VL_file_open
    failed to iterate over available VOL connector plugins
  File "H5PLpath.c", line 578, in H5PL__path_table_iterate
    can't iterate over plugins in plugin path '(null)'
  File "H5PLpath.c", line 620, in H5PL__path_table_iterate_process_path
    can't open directory: /fefs/home/elisa.visentin/mambaforge-pypy3/envs/magic-lst1/lib/hdf5/plugin
  File "H5VLcallback.c", line 3351, in H5VL__file_open
    open failed
  File "H5VLnative_file.c", line 97, in H5VL__native_file_open
    unable to open file
  File "H5Fint.c", line 1999, in H5F_open
    unable to read root group
  File "H5Groot.c", line 228, in H5G_mkroot
    can't check if symbol table message exists
  File "H5Omessage.c", line 845, in H5O_msg_exists
    unable to protect object header
  File "H5Oint.c", line 1051, in H5O_protect
    unable to load object header
  File "H5AC.c", line 1426, in H5AC_protect
    H5C_protect() failed
  File "H5C.c", line 2370, in H5C_protect
    can't load entry
  File "H5C.c", line 7315, in H5C__load_entry
    incorrect metadata checksum after all read attempts
  File "H5Ocache.c", line 203, in H5O__cache_get_final_load_size
    can't deserialize object header prefix
  File "H5Ocache.c", line 1202, in H5O__prefix_deserialize
    bad object header version number

End of HDF5 error back trace

Unable to open/create file '/fefs/aswg/workspace/elisa.visentin/MAGIC_LST_analysis/Crab_test_mcp/DL1_stereo/MC/gamma_test/theta_60.528_az_251.19/dl1_stereo_gamma_zd_60.528deg_az_251.19deg_LST1_MAGIC1_MAGIC2_run1601.h5'


```
They are files we produced with updated scripts, so I don't know if they can be fixed. It happens with ~1 file over some hundreds (obviously, all produced by the same scripts), this is why I tried skipping them. I don't know if they are the same that caused some problems to Julian in the MC automatic processing.

[dl1_stereo_gamma_zd_60.528deg_az_251.19deg_LST1_MAGIC1_MAGIC2_run1601.zip](https://github.com/cta-observatory/magic-cta-pipe/files/11199405/dl1_stereo_gamma_zd_60.528deg_az_251.19deg_LST1_MAGIC1_MAGIC2_run1601.zip)

**Comment by Elisa-Visentin** [comment]
Hi Alessio, 
I checked my logs too (I produced the files on the IT container, in  bash for loops on the queues). There seems to be nothing strange up to DL1-stereo 
```

Input file: /fefs/aswg/workspace/elisa.visentin/MAGIC_LST_analysis/Crab_test_mcp/DL1/MC/gamma_test/theta_60.528_az_251.19/dl1_gamma_zd_60.528deg_az_251.19deg_LST1_MAG
IC1_MAGIC2_run1601.h5

Is simulation: True

Telescope positions:
    1: <Quantity  -8.09000015 77.12666321  0.77666759  m>
    2: <Quantity   39.29999924 -62.5533371   -0.97333241  m>
    3: <Quantity  -31.21000099 -14.57333374   0.19666767  m> 

MAGIC-only analysis: False

Quality cuts: (intensity > 50) & (width > 0)

In total 1429 stereo events are found:
    M1_M2 (type 0): 1 events (0.1%)
    LST1_M1 (type 1): 160 events (11.2%)
    LST1_M2 (type 2): 271 events (19.0%)
    LST1_M1_M2 (type 3): 997 events (69.8%) 

Reconstructing the stereo parameters...
0 events
100 events
200 events
300 events
400 events
500 events
600 events
700 events
800 events
900 events
1000 events
1100 events
1200 events
1300 events
1400 events
1429 events

Output file: /fefs/aswg/workspace/elisa.visentin/MAGIC_LST_analysis/Crab_test_mcp/DL1_stereo/MC/gamma_test/theta_60.528_az_251.19/dl1_stereo_gamma_zd_60.528deg_az_251
.19deg_LST1_MAGIC1_MAGIC2_run1601.h5

Done.

Process time: 135 [sec]

```
But the output file cannot be read, both by the merge script (which we did not modified) and by Jupyter Notebooks (Pandas). Even the file size is OK... Same for the other few files that cause merging issues.

As for the scripts, we are using a pipeline updated to process 4 LST MCs (@ranieremenezes fork).

**Comment by jsitarek** [comment]
I am not sure if you still want to merge this,but the code looks a bit dangerous. Namely the first loop to find the first good file could break in different points due to the exception (I not sure if this can really happen, or if this exception is exclusively raised during opening up of the file), and this means that you could potentially end up with parts of the preparation of the output file executed multiple times.

**Comment by Elisa-Visentin** [comment]
This error was probably due to some cluster crash: after they solved the `disk quota` error we no more faced the same error with the current code, so we can close this PR as useless (I forgot this, sorry)

**Pull request closed without merging**
