### PR TITLE
In_out_versions

### PR DESCRIPTION
**Pull request by Elisa-Visentin**
Add the possibility to use, for each step, input data processed with an older MCP version wrt the current one

### CODE REVIEW

**Comment by jsitarek** [comment]
I checked the files and the changes look ok. Once a test is run we should also check the job_accounting script if it is not missing any input files because they are in a different folder

**Comment by Elisa-Visentin** [comment]
I am still testing it (IT queues are a bit stuck) but I will check both output and, as you suggested, job_accounting. Hopefully during the we...

**Comment by Elisa-Visentin** [comment]
Actually there was a small issue with directories (I have to create the directory with the current version name to be able to store the config. file for stereo and coincidence, or the scripts cannot read it). Now it should be fixed

**Comment by Elisa-Visentin** [comment]
As for job accounting, I plan to fix and check it today :)

**Review by jsitarek — APPROVED** [review]

**Comment by jsitarek** [comment]
looks good, shall we merge?

**Comment by Elisa-Visentin** [comment]
For me, yes (I finished all the tests and job accounting is fine)

**Pull request merged**
