### PR TITLE
Fix bug sources

### PR DESCRIPTION
**Pull request by FedericoDevoto757**
Fix an error in the scripts

### CODE REVIEW

**Comment by Elisa-Visentin** [comment]
@jsitarek could you check this? I introduced a bug in the 'management' of the name of the sources, sorry!

**Comment by jsitarek** [comment]
@FedericoDevoto757, can you clean up the PR such that it only has the intended code changes inside? The basic fix is the source name bugfix, and this exist_ok is also harmless, but the changes in LST run list text file file name and Merged directory can be potentially disturbing the code (unless they were intended).
Afterwards we can merge it

**Comment by FedericoDevoto757** [comment]
Good morning, both of the changes to the directory path name and the list_LST file were intended.

**Comment by jsitarek** [comment]
> Good morning, both of the changes to the directory path name and the list_LST file were intended.

thanks, I merged it now

**Pull request merged**
