### PR TITLE
Update environment to fix pip installation and fix CI

### PR DESCRIPTION
**Pull request by Elisa-Visentin**
- removed all dependencies already installed by `ctapipe`
- fixed `jupyterlab` to latest version compatible with `magic-cta-pipe`
- fixed `pyflakes` errors which were preventing the CI to succeed
- formatted all code with `black`

### CODE REVIEW

**Review by aleberti — APPROVED** [review]

**Comment by aleberti** [comment]
Next time you can simply create a branch in this repository and do the changes there, you have all the rights to write in this repo. This makes it easier for me (and others) to test, because I can simply change to the branch of the PR and test.

**Comment by aleberti** [comment]
In any case, it works nicely. I will merge it.

**Comment by Elisa-Visentin** [comment]
> Next time you can simply create a branch in this repository and do the changes there, you have all the rights to write in this repo. This makes it easier for me (and others) to test, because I can simply change to the branch of the PR and test.

When I created this PR I had no write access to this repository (we forgot to ask you for it) and I cannot persuade anybody to let me be a 'ghostwriter'.
Anyway thanks to @HealthyPear, too (for help and persuasion)

**Comment by aleberti** [comment]
Ah sorry, then my fault! Now you have the write rights, so no need to persuade anyone :)

**Comment by HealthyPear** [comment]
> In any case, it works nicely. I will merge it.

The maintainers team should make sure that the master branch is actually protected by the CI pipeline otherwise the next PR will fail again.

**Pull request merged**
