### PR TITLE
Add minimum and maximum values for theta2 and gammaness cuts.

### PR DESCRIPTION
**Pull request by aleberti**
This PR adds minimum and maximum values for the theta2 and gammaness cuts.

### CODE REVIEW

**Review by jsitarek — APPROVED** [review]
looks fine, thanks for implementing this

**Comment by aleberti** [comment]
Hi, just for reference, I post here the cuts before and after introducing these min/max values.

Before
```
Gammaness cuts (efficiency 0.9):         
        low                  high                center                cut
        TeV                  TeV                  TeV
-------------------- -------------------- -------------------- -------------------
                0.01 0.015848931924611134 0.012924465962305568                 1.0
0.015848931924611134 0.025118864315095794 0.020483898119853464                 1.0
0.025118864315095794 0.039810717055349734  0.03246479068522276                 1.0
0.039810717055349734  0.06309573444801933  0.05145322575168453                 1.0
 0.06309573444801933                  0.1  0.08154786722400967 0.22208333333333333
                 0.1  0.15848931924611143   0.1292446596230557 0.45300714285714283
 0.15848931924611143  0.25118864315095807  0.20483898119853475  0.6269880952380953
 0.25118864315095807   0.3981071705534973  0.32464790685222766  0.6273071428571428
  0.3981071705534973   0.6309573444801934   0.5145322575168454  0.6272499999999999
  0.6309573444801934                  1.0   0.8154786722400966  0.6638261904761903
                 1.0    1.584893192461114    1.292446596230557  0.7057261904761905
   1.584893192461114   2.5118864315095824    2.048389811985348  0.7423904761904762
  2.5118864315095824    3.981071705534973   3.2464790685222775              0.7925
   3.981071705534973    6.309573444801936    5.145322575168454             0.82125
   6.309573444801936                 10.0    8.154786722400967  0.8322666666666667
                10.0   15.848931924611142   12.924465962305572  0.8184166666666666
  15.848931924611142    25.11886431509582    20.48389811985348  0.7919619047619048
   25.11886431509582   39.810717055349734    32.46479068522278  0.6448958333333334
  39.810717055349734   63.095734448019364    51.45322575168455           0.4954125
  63.095734448019364                100.0    81.54786722400968                 1.0

Theta2 cuts (efficiency 0.75):
        low                  high                center                cut
        TeV                  TeV                  TeV                  deg
-------------------- -------------------- -------------------- -------------------
                0.01 0.015848931924611134 0.012924465962305568                 0.0
0.015848931924611134 0.025118864315095794 0.020483898119853464                 0.0
0.025118864315095794 0.039810717055349734  0.03246479068522276                 0.0
0.039810717055349734  0.06309573444801933  0.05145322575168453                 0.0
 0.06309573444801933                  0.1  0.08154786722400967 0.38931159892087985
                 0.1  0.15848931924611143   0.1292446596230557 0.35414963422499834
 0.15848931924611143  0.25118864315095807  0.20483898119853475 0.29450831697082214
 0.25118864315095807   0.3981071705534973  0.32464790685222766 0.22921937185664365
  0.3981071705534973   0.6309573444801934   0.5145322575168454  0.1823703042897002
  0.6309573444801934                  1.0   0.8154786722400966  0.1510437515025016
                 1.0    1.584893192461114    1.292446596230557  0.1287943806011821
   1.584893192461114   2.5118864315095824    2.048389811985348 0.11292559962924749
  2.5118864315095824    3.981071705534973   3.2464790685222775 0.10324652701637516
   3.981071705534973    6.309573444801936    5.145322575168454  0.1000966953464705
   6.309573444801936                 10.0    8.154786722400967 0.10194451500956396
                10.0   15.848931924611142   12.924465962305572 0.10430737134825484
  15.848931924611142    25.11886431509582    20.48389811985348  0.1132066829872612
   25.11886431509582   39.810717055349734    32.46479068522278 0.11942548269998761
  39.810717055349734   63.095734448019364    51.45322575168455 0.09733676321255108
  63.095734448019364                100.0    81.54786722400968                 0.0
```

and after:

```
Gammaness cuts (efficiency: 0.9):
        low                  high                center                cut
        TeV                  TeV                  TeV
-------------------- -------------------- -------------------- -------------------
                0.01 0.015848931924611134 0.012924465962305568                0.05
0.015848931924611134 0.025118864315095794 0.020483898119853464                0.05
0.025118864315095794 0.039810717055349734  0.03246479068522276                0.05
0.039810717055349734  0.06309573444801933  0.05145322575168453                0.05
 0.06309573444801933                  0.1  0.08154786722400967 0.22208333333333333
                 0.1  0.15848931924611143   0.1292446596230557 0.45300714285714283
 0.15848931924611143  0.25118864315095807  0.20483898119853475  0.6269880952380953
 0.25118864315095807   0.3981071705534973  0.32464790685222766  0.6273071428571428
  0.3981071705534973   0.6309573444801934   0.5145322575168454  0.6272499999999999
  0.6309573444801934                  1.0   0.8154786722400966  0.6638261904761903
                 1.0    1.584893192461114    1.292446596230557  0.7057261904761905
   1.584893192461114   2.5118864315095824    2.048389811985348  0.7423904761904762
  2.5118864315095824    3.981071705534973   3.2464790685222775              0.7925
   3.981071705534973    6.309573444801936    5.145322575168454             0.82125
   6.309573444801936                 10.0    8.154786722400967  0.8322666666666667
                10.0   15.848931924611142   12.924465962305572  0.8184166666666666
  15.848931924611142    25.11886431509582    20.48389811985348  0.7919619047619048
   25.11886431509582   39.810717055349734    32.46479068522278  0.6448958333333334
  39.810717055349734   63.095734448019364    51.45322575168455           0.4954125
  63.095734448019364                100.0    81.54786722400968                0.05

Theta cuts (efficiency: 0.75):
        low                  high                center                cut
        TeV                  TeV                  TeV                  deg
-------------------- -------------------- -------------------- -------------------
                0.01 0.015848931924611134 0.012924465962305568                0.45
0.015848931924611134 0.025118864315095794 0.020483898119853464                0.45
0.025118864315095794 0.039810717055349734  0.03246479068522276                0.45
0.039810717055349734  0.06309573444801933  0.05145322575168453                0.45
 0.06309573444801933                  0.1  0.08154786722400967 0.38931159892087985
                 0.1  0.15848931924611143   0.1292446596230557 0.35414963422499834
 0.15848931924611143  0.25118864315095807  0.20483898119853475 0.29450831697082214
 0.25118864315095807   0.3981071705534973  0.32464790685222766 0.22921937185664365
  0.3981071705534973   0.6309573444801934   0.5145322575168454  0.1823703042897002
  0.6309573444801934                  1.0   0.8154786722400966  0.1510437515025016
                 1.0    1.584893192461114    1.292446596230557  0.1287943806011821
   1.584893192461114   2.5118864315095824    2.048389811985348 0.11292559962924749
  2.5118864315095824    3.981071705534973   3.2464790685222775 0.10324652701637516
   3.981071705534973    6.309573444801936    5.145322575168454  0.1000966953464705
   6.309573444801936                 10.0    8.154786722400967 0.10194451500956396
                10.0   15.848931924611142   12.924465962305572 0.10430737134825484
  15.848931924611142    25.11886431509582    20.48389811985348  0.1132066829872612
   25.11886431509582   39.810717055349734    32.46479068522278 0.11942548269998761
  39.810717055349734   63.095734448019364    51.45322575168455                 0.1
  63.095734448019364                100.0    81.54786722400968                0.45
```

**Comment by YoshikiOhtani** [comment]
Hi @aleberti, thanks for the pull request. It looks fine, but I have a question - are the min/max values the ones used in the MARS analysis? It looks that setting the min/max values only change the following theta cut (set to the min value) and so the spectrum does not change between before and after the changes?

```
Theta cuts (efficiency: 0.75):
from 
39.810717055349734   63.095734448019364    51.45322575168455 0.09733676321255108
to
39.810717055349734   63.095734448019364    51.45322575168455                 0.1
```

**Comment by aleberti** [comment]
> Hi @aleberti, thanks for the pull request. It looks fine, but I have a question - are the min/max values the ones used in the MARS analysis? It looks that setting the min/max values only change the following theta cut (set to the min value) and so the spectrum does not change between before and after the changes?
> 
> ```
> Theta cuts (efficiency: 0.75):
> from 
> 39.810717055349734   63.095734448019364    51.45322575168455 0.09733676321255108
> to
> 39.810717055349734   63.095734448019364    51.45322575168455                 0.1
> ```

yes, indeed the SED did not change with these cuts. Just for testing, I modified locally `lst1_magic_create_irf.py` to calculate the cuts in theta2 (and not in theta), and also in this case the only value changed is the one but last (of course the limits have been changed to the square of 0.1 and 0.45, which are 0.01 and ~0.2). Here below the table:

```
Theta cuts (efficiency: 0.75):
        low                  high                center                cut
        TeV                  TeV                  TeV                  deg2
-------------------- -------------------- -------------------- --------------------
                0.01 0.015848931924611134 0.012924465962305568                  0.2
0.015848931924611134 0.025118864315095794 0.020483898119853464                  0.2
0.025118864315095794 0.039810717055349734  0.03246479068522276                  0.2
0.039810717055349734  0.06309573444801933  0.05145322575168453                  0.2
 0.06309573444801933                  0.1  0.08154786722400967   0.1515635228594771
                 0.1  0.15848931924611143   0.1292446596230557  0.12542196342170012
 0.15848931924611143  0.25118864315095807  0.20483898119853475  0.08673514878773833
 0.25118864315095807   0.3981071705534973  0.32464790685222766 0.052541520435618674
  0.3981071705534973   0.6309573444801934   0.5145322575168454  0.03325892788671784
  0.6309573444801934                  1.0   0.8154786722400966 0.022814214867949455
                 1.0    1.584893192461114    1.292446596230557 0.016587992522568325
   1.584893192461114   2.5118864315095824    2.048389811985348  0.01275219105285453
  2.5118864315095824    3.981071705534973   3.2464790685222775 0.010659845340943086
   3.981071705534973    6.309573444801936    5.145322575168454 0.010019348430400053
   6.309573444801936                 10.0    8.154786722400967 0.010392684141423301
                10.0   15.848931924611142   12.924465962305572 0.010880027717582735
  15.848931924611142    25.11886431509582    20.48389811985348 0.012815753072978638
   25.11886431509582   39.810717055349734    32.46479068522278 0.014262450707125781
  39.810717055349734   63.095734448019364    51.45322575168455                 0.01
  63.095734448019364                100.0    81.54786722400968                  0.2

```

**Review by YoshikiOhtani — APPROVED** [review]
I see, thanks for testing. I will merge this to the master now.

**Pull request merged**
